<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">getSocketClient</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgcGlwZWxpbmVDdXJzb3IgPSBwaXBlbGluZS5nZXRDdXJzb3IoKTsNClN0cmlu
ZwlOQU1FID0gSURhdGFVdGlsLmdldFN0cmluZyggcGlwZWxpbmVDdXJzb3IsICJOQU1FIiApOw0K
cGlwZWxpbmVDdXJzb3IuZGVzdHJveSgpOw0KDQpJRGF0YSBDbGllbnRQb3J0SW5mbyA9IG51bGw7
DQpTdHJpbmcgZXJyb3JNc2cgPSAiIjsNCg0KdHJ5IHsNCglDbGllbnRQb3J0SW5mbyA9IHNNYW5h
Z2VyLmdldFNvY2tldENsaWVudCggTkFNRSApOw0KCQ0KCWlmICggQ2xpZW50UG9ydEluZm8gPT0g
bnVsbCApIHsNCgkJZXJyb3JNc2cgPSBOQU1FICsgIiBcdUM1RDAgXHVCMzAwXHVENTVDIFNvY2tl
dCBDbGllbnQgXHVDODE1XHVCQ0Y0XHVBQzAwIFx1QzVDNlx1QzJCNVx1QjJDOFx1QjJFNC4iOw0K
CX0NCn0gY2F0Y2ggKCBFeGNlcHRpb24gZSApIHsNCgllcnJvck1zZyA9IGUudG9TdHJpbmcoKTsN
Cn0NCg0KSURhdGFDdXJzb3IgcGlwZWxpbmVDdXJzb3JfMSA9IHBpcGVsaW5lLmdldEN1cnNvcigp
Ow0KSURhdGFVdGlsLnB1dCggcGlwZWxpbmVDdXJzb3JfMSwgImVycm9yTXNnIiwgZXJyb3JNc2cg
KTsNCklEYXRhVXRpbC5wdXQoIHBpcGVsaW5lQ3Vyc29yXzEsICJDbGllbnRQb3J0SW5mbyIsIENs
aWVudFBvcnRJbmZvICk7DQpwaXBlbGluZUN1cnNvcl8xLmRlc3Ryb3koKTs=</value>
</Values>
