<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">downServerSocket</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IJcGlwZWxpbmVDdXJzb3IgPSBwaXBlbGluZS5nZXRDdXJzb3IoKTsNClN0cmlu
ZyBwb3J0TnVtYmVyID0gSURhdGFVdGlsLmdldFN0cmluZyggcGlwZWxpbmVDdXJzb3IsICJwb3J0
TnVtYmVyIiApOw0KU3RyaW5nIHRocmVhZFBvb2wgPSBJRGF0YVV0aWwuZ2V0U3RyaW5nKCBwaXBl
bGluZUN1cnNvciwgInRocmVhZFBvb2wiICk7DQpTdHJpbmcgb25saW5lID0gSURhdGFVdGlsLmdl
dFN0cmluZyggcGlwZWxpbmVDdXJzb3IsICJvbmxpbmUiICk7DQpTdHJpbmcgc2VydmljZVBhdGgg
PSBJRGF0YVV0aWwuZ2V0U3RyaW5nKCBwaXBlbGluZUN1cnNvciwgInNlcnZpY2VQYXRoIiApOw0K
aW50IHBudW0gPSBJbnRlZ2VyLnBhcnNlSW50KCBwb3J0TnVtYmVyICk7DQpwaXBlbGluZUN1cnNv
ci5kZXN0cm95KCk7DQoNClN0cmluZyBkb3duZWQgPSAidHJ1ZSI7DQpTdHJpbmcgZXJyb3JNc2cg
PSAiIjsNCg0KdHJ5IHsNCglzTWFuYWdlci5kb3duU2VydmVyU29ja2V0KCBwbnVtLCB0aHJlYWRQ
b29sLCBvbmxpbmUsIHNlcnZpY2VQYXRoICk7DQp9IGNhdGNoKCBFeGNlcHRpb24gZSApIHsNCglk
ZWJ1Z0xvZ2dlci5wcmludExvZ0F0SVMoICIjIyMgZG93blNvY2tldFNlcnZlciBFcnJvcihQb3J0
IDogIiArIHBvcnROdW1iZXIgKyAiKSA6ICIgKyBlLnRvU3RyaW5nKCksICJhc3luY2giICk7DQoJ
ZG93bmVkID0gImZhbHNlIjsNCgllcnJvck1zZyA9IGUudG9TdHJpbmcoKTsNCn0NCg0KSURhdGFD
dXJzb3IgcGlwZWxpbmVDdXJzb3JfMSA9IHBpcGVsaW5lLmdldEN1cnNvcigpOw0KSURhdGFVdGls
LnB1dCggcGlwZWxpbmVDdXJzb3JfMSwgImRvd25lZCIsIGRvd25lZCApOw0KSURhdGFVdGlsLnB1
dCggcGlwZWxpbmVDdXJzb3JfMSwgImVycm9yTXNnIiwgZXJyb3JNc2cgKTsNCnBpcGVsaW5lQ3Vy
c29yXzEuZGVzdHJveSgpOw==</value>
</Values>
