<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">removeOnlineSendStatus</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgcGlwZWxpbmVDdXJzb3IgPSBwaXBlbGluZS5nZXRDdXJzb3IoKTsNClN0cmlu
ZwluYW1lID0gSURhdGFVdGlsLmdldFN0cmluZyggcGlwZWxpbmVDdXJzb3IsICJuYW1lIiApOw0K
cGlwZWxpbmVDdXJzb3IuZGVzdHJveSgpOw0KDQpTdHJpbmcgZXJyb3JNc2cgPSAiIjsNCg0KdHJ5
IHsNCgkvLyBPbmxpbmVTZW5kU3RhdHVzTGlzdCBIYXNodGFibGUgXHVDNUQwXHVDMTFDIFx1QzBB
RFx1QzgxQw0KCXNNYW5hZ2VyLnJlbW92ZU9ubGluZVNlbmRTdGF0dXMoIG5hbWUgKTsNCn0gY2F0
Y2ggKCBFeGNlcHRpb24gZSApIHsNCgllcnJvck1zZyA9IGUudG9TdHJpbmcoKTsNCn0NCg0KSURh
dGFDdXJzb3IgcGlwZWxpbmVDdXJzb3JfMSA9IHBpcGVsaW5lLmdldEN1cnNvcigpOw0KSURhdGFV
dGlsLnB1dCggcGlwZWxpbmVDdXJzb3JfMSwgImVycm9yTXNnIiwgZXJyb3JNc2cgKTsNCnBpcGVs
aW5lQ3Vyc29yXzEuZGVzdHJveSgpOw==</value>
</Values>
