<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">getOnlineSocketClient</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgcGlwZWxpbmVDdXJzb3IgPSBwaXBlbGluZS5nZXRDdXJzb3IoKTsNClN0cmlu
ZwlOQU1FID0gSURhdGFVdGlsLmdldFN0cmluZyggcGlwZWxpbmVDdXJzb3IsICJOQU1FIiApOw0K
cGlwZWxpbmVDdXJzb3IuZGVzdHJveSgpOw0KDQpJRGF0YSBDbGllbnRTb2NrZXRJbmZvID0gbnVs
bDsNClN0cmluZyBlcnJvck1zZyA9ICIiOw0KDQp0cnkgew0KCUNsaWVudFNvY2tldEluZm8gPSBz
TWFuYWdlci5nZXRPbmxpbmVTb2NrZXRDbGllbnQoIE5BTUUgKTsNCgkNCglpZiAoIENsaWVudFNv
Y2tldEluZm8gPT0gbnVsbCApIHsNCgkJZXJyb3JNc2cgPSBOQU1FICsgIlx1QzVEMCBcdUIzMDBc
dUQ1NUMgT25saW5lIFNvY2tldCBDb25uZWN0aW9uXHVDNzc0IE9mZmxpbmUgXHVDMEMxXHVEMERD
XHVDNzg1XHVCMkM4XHVCMkU0LiI7DQoJfQ0KfSBjYXRjaCAoIEV4Y2VwdGlvbiBlICkgew0KCWVy
cm9yTXNnID0gZS50b1N0cmluZygpOw0KfQ0KDQpJRGF0YUN1cnNvciBwaXBlbGluZUN1cnNvcl8x
ID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQpJRGF0YVV0aWwucHV0KCBwaXBlbGluZUN1cnNvcl8x
LCAiZXJyb3JNc2ciLCBlcnJvck1zZyApOw0KSURhdGFVdGlsLnB1dCggcGlwZWxpbmVDdXJzb3Jf
MSwgIkNsaWVudFNvY2tldEluZm8iLCBDbGllbnRTb2NrZXRJbmZvICk7DQpwaXBlbGluZUN1cnNv
cl8xLmRlc3Ryb3koKTs=</value>
</Values>
