<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">getOnlineHealthCheck</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgcGlwZWxpbmVDdXJzb3IgPSBwaXBlbGluZS5nZXRDdXJzb3IoKTsNClN0cmlu
ZwluYW1lID0gSURhdGFVdGlsLmdldFN0cmluZyggcGlwZWxpbmVDdXJzb3IsICJuYW1lIiApOw0K
cGlwZWxpbmVDdXJzb3IuZGVzdHJveSgpOw0KDQpJRGF0YSBPbmxpbmVIZWFsdGhDaGVja0luZm8g
PSBudWxsOw0KU3RyaW5nIGVycm9yTXNnID0gIiI7DQoNCnRyeSB7DQoJT25saW5lSGVhbHRoQ2hl
Y2tJbmZvID0gc01hbmFnZXIuZ2V0T25saW5lSGVhbHRoQ2hlY2soIG5hbWUgKTsNCgkNCglpZiAo
IE9ubGluZUhlYWx0aENoZWNrSW5mbyA9PSBudWxsICkgew0KCQllcnJvck1zZyA9IG5hbWUgKyAi
IFx1QzVEMCBcdUIzMDBcdUQ1NUMgT25saW5lIEhlYWx0aCBDaGVjayBTZXJ2aWNlIFx1QzgxNVx1
QkNGNFx1QUMwMCBcdUM4NzRcdUM3QUNcdUQ1NThcdUM5QzAgXHVDNTRBXHVDMkI1XHVCMkM4XHVC
MkU0LiI7DQoJfQ0KfSBjYXRjaCAoIEV4Y2VwdGlvbiBlICkgew0KCWVycm9yTXNnID0gZS50b1N0
cmluZygpOw0KfQ0KDQpJRGF0YUN1cnNvciBwaXBlbGluZUN1cnNvcl8xID0gcGlwZWxpbmUuZ2V0
Q3Vyc29yKCk7DQpJRGF0YVV0aWwucHV0KCBwaXBlbGluZUN1cnNvcl8xLCAiZXJyb3JNc2ciLCBl
cnJvck1zZyApOw0KSURhdGFVdGlsLnB1dCggcGlwZWxpbmVDdXJzb3JfMSwgIk9ubGluZUhlYWx0
aENoZWNrSW5mbyIsIE9ubGluZUhlYWx0aENoZWNrSW5mbyApOw0KcGlwZWxpbmVDdXJzb3JfMS5k
ZXN0cm95KCk7</value>
</Values>
