<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">putOnlineReconnectingServer</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgcGlwZWxpbmVDdXJzb3IgPSBwaXBlbGluZS5nZXRDdXJzb3IoKTsNClN0cmlu
ZyBOQU1FID0gSURhdGFVdGlsLmdldFN0cmluZyggcGlwZWxpbmVDdXJzb3IsICJOQU1FIiApOw0K
SURhdGEgT25saW5lUmVjb25uZWN0aW5nU2VydmVyID0gSURhdGFVdGlsLmdldElEYXRhKCBwaXBl
bGluZUN1cnNvciwgIk9ubGluZVJlY29ubmVjdGluZ1NlcnZlciIgKTsNCnBpcGVsaW5lQ3Vyc29y
LmRlc3Ryb3koKTsNCg0KU3RyaW5nIGVycm9yTXNnID0gIiI7DQoNCnRyeSB7DQoJc01hbmFnZXIu
cHV0T25saW5lUmVjb25uZWN0aW5nU2VydmVyKCBOQU1FLCBPbmxpbmVSZWNvbm5lY3RpbmdTZXJ2
ZXIgKTsNCn0gY2F0Y2ggKCBFeGNlcHRpb24gZSApIHsNCgllcnJvck1zZyA9IGUudG9TdHJpbmco
KTsNCn0NCg0KSURhdGFDdXJzb3IgcGlwZWxpbmVDdXJzb3JfMSA9IHBpcGVsaW5lLmdldEN1cnNv
cigpOw0KSURhdGFVdGlsLnB1dCggcGlwZWxpbmVDdXJzb3JfMSwgImVycm9yTXNnIiwgZXJyb3JN
c2cgKTsNCnBpcGVsaW5lQ3Vyc29yXzEuZGVzdHJveSgpOw==</value>
</Values>
