<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">getOnlineServerListener</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgcGlwZWxpbmVDdXJzb3IgPSBwaXBlbGluZS5nZXRDdXJzb3IoKTsNClN0cmlu
ZwlzZXNzaW9uTmFtZSA9IElEYXRhVXRpbC5nZXRTdHJpbmcoIHBpcGVsaW5lQ3Vyc29yLCAibmFt
ZSIgKTsNCnBpcGVsaW5lQ3Vyc29yLmRlc3Ryb3koKTsNCg0KSURhdGEgT25saW5lTGlzdGVuZXJJ
bmZvID0gbnVsbDsNClN0cmluZyBlcnJvck1zZyA9ICIiOw0KDQp0cnkgew0KCU9ubGluZUxpc3Rl
bmVySW5mbyA9IHNNYW5hZ2VyLmdldE9ubGluZVNlcnZlckxpc3RlbmVyKCBzZXNzaW9uTmFtZSAp
Ow0KCQ0KCWlmICggT25saW5lTGlzdGVuZXJJbmZvID09IG51bGwgKSB7DQoJCWVycm9yTXNnID0g
c2Vzc2lvbk5hbWUgKyAiIFx1QzVEMCBcdUIzMDBcdUQ1NUMgT25saW5lIFNlcnZlciBMaXN0ZW5l
ciBcdUM4MTVcdUJDRjRcdUFDMDAgXHVDODc0XHVDN0FDXHVENTU4XHVDOUMwIFx1QzU0QVx1QzJC
NVx1QjJDOFx1QjJFNC4iOw0KCX0NCn0gY2F0Y2ggKCBFeGNlcHRpb24gZSApIHsNCgllcnJvck1z
ZyA9IGUudG9TdHJpbmcoKTsNCn0NCg0KSURhdGFDdXJzb3IgcGlwZWxpbmVDdXJzb3JfMSA9IHBp
cGVsaW5lLmdldEN1cnNvcigpOw0KSURhdGFVdGlsLnB1dCggcGlwZWxpbmVDdXJzb3JfMSwgImVy
cm9yTXNnIiwgZXJyb3JNc2cgKTsNCklEYXRhVXRpbC5wdXQoIHBpcGVsaW5lQ3Vyc29yXzEsICJP
bmxpbmVMaXN0ZW5lckluZm8iLCBPbmxpbmVMaXN0ZW5lckluZm8gKTsNCnBpcGVsaW5lQ3Vyc29y
XzEuZGVzdHJveSgpOw==</value>
</Values>
