<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">setSessionCount</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgcGlwZWxpbmVDdXJzb3IgPSBwaXBlbGluZS5nZXRDdXJzb3IoKTsNCmludAlw
b3J0TnVtYmVyID0gSURhdGFVdGlsLmdldEludCggcGlwZWxpbmVDdXJzb3IsICJwb3J0TnVtYmVy
IiwgMCApOw0KaW50CXNlc3Npb25Db3VudCA9IElEYXRhVXRpbC5nZXRJbnQoIHBpcGVsaW5lQ3Vy
c29yLCAic2Vzc2lvbkNvdW50IiwgMCApOw0KcGlwZWxpbmVDdXJzb3IuZGVzdHJveSgpOw0KDQpT
dHJpbmcgZXJyb3JNc2cgPSAiIjsNCg0KdHJ5IHsNCglzTWFuYWdlci5zZXRTZXNzaW9uQ291bnQo
IHBvcnROdW1iZXIsIHNlc3Npb25Db3VudCApOw0KfSBjYXRjaCAoIEV4Y2VwdGlvbiBlICkgew0K
CWVycm9yTXNnID0gZS50b1N0cmluZygpOw0KfQ0KDQpJRGF0YUN1cnNvciBwaXBlbGluZUN1cnNv
cl8xID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQpJRGF0YVV0aWwucHV0KCBwaXBlbGluZUN1cnNv
cl8xLCAiZXJyb3JNc2ciLCBlcnJvck1zZyApOw0KcGlwZWxpbmVDdXJzb3JfMS5kZXN0cm95KCk7
</value>
</Values>
