<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">convertBytesToHexString</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgcGlwZWxpbmVDdXJzb3IgPSBwaXBlbGluZS5nZXRDdXJzb3IoKTsNCmJ5dGVb
XSBpbnB1dEJ5dGVzID0gKCBieXRlW10gKUlEYXRhVXRpbC5nZXQoIHBpcGVsaW5lQ3Vyc29yLCAi
aW5wdXRCeXRlcyIgKTsNCnBpcGVsaW5lQ3Vyc29yLmRlc3Ryb3koKTsNCg0KU3RyaW5nQnVmZmVy
IHJlc3VsdCA9IG5ldyBTdHJpbmdCdWZmZXIoKTsNCg0KLyoNCmZvciAoIGJ5dGUgYiA6IGlucHV0
Qnl0ZXMgKSB7DQoJcmVzdWx0LmFwcGVuZCggSW50ZWdlci50b1N0cmluZyggKCBiICYgMHhGMCAp
ID4+IDQsIDE2ICkgKTsNCglyZXN1bHQuYXBwZW5kKCBJbnRlZ2VyLnRvU3RyaW5nKCBiICYgMHgw
RiwgMTYgKSApOw0KfQ0KKi8NCg0KZm9yICggaW50IGkgPSAwOyBpIDwgaW5wdXRCeXRlcy5sZW5n
dGg7IGkrKyApIHsNCglyZXN1bHQuYXBwZW5kKCBJbnRlZ2VyLnRvSGV4U3RyaW5nKCAweDAxMDAg
KyAoIGlucHV0Qnl0ZXNbIGkgXSAmIDB4MDBGRiApICkuc3Vic3RyaW5nKCAxICkgKTsNCn0NCg0K
SURhdGFDdXJzb3IgcGlwZWxpbmVDdXJzb3JfMSA9IHBpcGVsaW5lLmdldEN1cnNvcigpOw0KSURh
dGFVdGlsLnB1dCggcGlwZWxpbmVDdXJzb3JfMSwgImhleFN0cmluZyIsIHJlc3VsdC50b1N0cmlu
ZygpICk7DQpwaXBlbGluZUN1cnNvcl8xLmRlc3Ryb3koKTs=</value>
</Values>
