<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">checkSocketStatus</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IJcGlwZWxpbmVDdXJzb3IgPSBwaXBlbGluZS5nZXRDdXJzb3IoKTsNClNvY2tl
dCBzb2NrZXQgPSAoIFNvY2tldCApSURhdGFVdGlsLmdldCggcGlwZWxpbmVDdXJzb3IsICJzb2Nr
ZXQiICk7DQpwaXBlbGluZUN1cnNvci5kZXN0cm95KCk7DQoNClN0cmluZyBpc0Nsb3NlZAk9ICIi
Ow0KU3RyaW5nIGlzQ29ubmVjdGVkID0gIiI7DQoNCnRyeSB7DQoJaXNDbG9zZWQgPSBzb2NrZXQu
aXNDbG9zZWQoICkgKyAiIiA7DQoJaXNDb25uZWN0ZWQJPSBzb2NrZXQuaXNDb25uZWN0ZWQoKSAr
ICIiOw0KfSBjYXRjaCggRXhjZXB0aW9uIGUgKXsNCglkZWJ1Z0xvZ2dlci5wcmludExvZ0F0SVMo
ICIjIyMgY2hlY2tTb2NrZXRTdGF0dXMgRXJyb3IgOiAiICsgZS50b1N0cmluZygpLCAiYXN5bmNo
IiApOw0KfQ0KDQpJRGF0YUN1cnNvciBwaXBlbGluZUN1cnNvcl8xID0gcGlwZWxpbmUuZ2V0Q3Vy
c29yKCk7DQpJRGF0YVV0aWwucHV0KCBwaXBlbGluZUN1cnNvcl8xLCAiaXNDbG9zZWQiLCBpc0Ns
b3NlZCApOw0KSURhdGFVdGlsLnB1dCggcGlwZWxpbmVDdXJzb3JfMSwgImlzQ29ubmVjdGVkIiwg
aXNDb25uZWN0ZWQgKTsNCnBpcGVsaW5lQ3Vyc29yXzEuZGVzdHJveSgpOw==</value>
</Values>
