<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">convertToRecordByDelim</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgcGlwZWxpbmVDdXJzb3IgPSBwaXBlbGluZS5nZXRDdXJzb3IoKTsNClN0cmlu
ZyBkYXRhUmVjb3JkID0gSURhdGFVdGlsLmdldFN0cmluZyggcGlwZWxpbmVDdXJzb3IsICJkYXRh
UmVjb3JkIiApOw0KU3RyaW5nIGRlbGltID0gSURhdGFVdGlsLmdldFN0cmluZyggcGlwZWxpbmVD
dXJzb3IsICJkZWxpbSIgKTsNCnBpcGVsaW5lQ3Vyc29yLmRlc3Ryb3koKTsNCg0KU3RyaW5nQnVm
ZmVyIHN0ckJ1ZmZlciA9IG5ldyBTdHJpbmdCdWZmZXIoKTsNClN0cmluZyBvdXREYXRhUmVjb3Jk
cyA9ICIiOw0KDQpTdHJpbmdbXSByZWNvcmRMaXN0ID0gZGF0YVJlY29yZC5zcGxpdCggZGVsaW0g
KTsNCg0KZm9yICggaW50IGkgPSAwOyBpIDwgcmVjb3JkTGlzdC5sZW5ndGg7IGkrKyApIHsNCglz
dHJCdWZmZXIuYXBwZW5kKCByZWNvcmRMaXN0WyBpIF0gKTsNCglzdHJCdWZmZXIuYXBwZW5kKCAi
XG4iICk7DQp9DQoNCm91dERhdGFSZWNvcmRzID0gc3RyQnVmZmVyLnRvU3RyaW5nKCk7DQoNCnN0
ckJ1ZmZlciA9IG51bGw7DQoNCklEYXRhQ3Vyc29yIHBpcGVsaW5lQ3Vyc29yXzEgPSBwaXBlbGlu
ZS5nZXRDdXJzb3IoKTsNCklEYXRhVXRpbC5wdXQoIHBpcGVsaW5lQ3Vyc29yXzEsICJvdXREYXRh
UmVjb3JkcyIsIG91dERhdGFSZWNvcmRzICk7DQpwaXBlbGluZUN1cnNvcl8xLmRlc3Ryb3koKTs=
</value>
</Values>
