<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">getCustomVariable</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgcGlwZWxpbmVDdXJzb3IgPSBwaXBlbGluZS5nZXRDdXJzb3IoKTsNClN0cmlu
Zwl2YXJpYWJsZU5hbWUgPSBJRGF0YVV0aWwuZ2V0U3RyaW5nKCBwaXBlbGluZUN1cnNvciwgInZh
cmlhYmxlTmFtZSIgKTsNCnBpcGVsaW5lQ3Vyc29yLmRlc3Ryb3koKTsNCg0KU3RyaW5nIGVycm9y
TXNnID0gIiI7DQpJRGF0YSBDdXN0b21WYXJpYWJsZUluZm8gPSBudWxsOw0KDQp0cnkgew0KCUN1
c3RvbVZhcmlhYmxlSW5mbyA9IHNNYW5hZ2VyLmdldEN1c3RvbVZhcmlhYmxlKCB2YXJpYWJsZU5h
bWUgKTsNCgkNCglpZiAoIEN1c3RvbVZhcmlhYmxlSW5mbyA9PSBudWxsICkgew0KCQllcnJvck1z
ZyA9IHZhcmlhYmxlTmFtZSArICIgXHVBQzAwIEN1c3RvbSBWYXJpYWJsZSBMaXN0IFx1QzVEMCBc
dUM4NzRcdUM3QUNcdUQ1NThcdUM5QzAgXHVDNTRBXHVDMkI1XHVCMkM4XHVCMkU0LiI7DQoJfQ0K
fSBjYXRjaCAoIEV4Y2VwdGlvbiBlICkgew0KCWVycm9yTXNnID0gZS50b1N0cmluZygpOw0KfQ0K
DQpJRGF0YUN1cnNvciBwaXBlbGluZUN1cnNvcl8xID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQpJ
RGF0YVV0aWwucHV0KCBwaXBlbGluZUN1cnNvcl8xLCAiZXJyb3JNc2ciLCBlcnJvck1zZyApOw0K
SURhdGFVdGlsLnB1dCggcGlwZWxpbmVDdXJzb3JfMSwgIkN1c3RvbVZhcmlhYmxlSW5mbyIsIEN1
c3RvbVZhcmlhYmxlSW5mbyApOw0KcGlwZWxpbmVDdXJzb3JfMS5kZXN0cm95KCk7</value>
</Values>
