<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">getBusinessInterface</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgcGlwZWxpbmVDdXJzb3IgPSBwaXBlbGluZS5nZXRDdXJzb3IoKTsNClN0cmlu
ZwluYW1lID0gSURhdGFVdGlsLmdldFN0cmluZyggcGlwZWxpbmVDdXJzb3IsICJuYW1lIiApOw0K
cGlwZWxpbmVDdXJzb3IuZGVzdHJveSgpOw0KDQpJRGF0YSBCdXNpbmVzc0ludGVyZmFjZUluZm8g
PSBudWxsOw0KU3RyaW5nIGVycm9yTXNnID0gIiI7DQoNCnRyeSB7DQoJQnVzaW5lc3NJbnRlcmZh
Y2VJbmZvID0gc01hbmFnZXIuZ2V0QnVzaW5lc3NJbnRlcmZhY2UoIG5hbWUgKTsNCgkNCglpZiAo
IEJ1c2luZXNzSW50ZXJmYWNlSW5mbyA9PSBudWxsICkgew0KCQllcnJvck1zZyA9IG5hbWUgKyAi
IFx1QUMwMCBCdXNpbmVzcyBJbnRlcmZhY2UgTGlzdCBcdUM1RDAgXHVDODc0XHVDN0FDXHVENTU4
XHVDOUMwIFx1QzU0QVx1QzJCNVx1QjJDOFx1QjJFNC4iOw0KCX0NCn0gY2F0Y2ggKCBFeGNlcHRp
b24gZSApIHsNCgllcnJvck1zZyA9IGUudG9TdHJpbmcoKTsNCn0NCg0KSURhdGFDdXJzb3IgcGlw
ZWxpbmVDdXJzb3JfMSA9IHBpcGVsaW5lLmdldEN1cnNvcigpOw0KSURhdGFVdGlsLnB1dCggcGlw
ZWxpbmVDdXJzb3JfMSwgImVycm9yTXNnIiwgZXJyb3JNc2cgKTsNCklEYXRhVXRpbC5wdXQoIHBp
cGVsaW5lQ3Vyc29yXzEsICJCdXNpbmVzc0ludGVyZmFjZUluZm8iLCBCdXNpbmVzc0ludGVyZmFj
ZUluZm8gKTsNCnBpcGVsaW5lQ3Vyc29yXzEuZGVzdHJveSgpOw==</value>
</Values>
