<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">convertStringToHexString</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgcGlwZWxpbmVDdXJzb3IgPSBwaXBlbGluZS5nZXRDdXJzb3IoKTsNClN0cmlu
ZyBpbnB1dFN0cmluZyA9IElEYXRhVXRpbC5nZXRTdHJpbmcoIHBpcGVsaW5lQ3Vyc29yLCAiaW5w
dXRTdHJpbmciICk7DQpTdHJpbmcgZW5jb2RpbmcgPSBJRGF0YVV0aWwuZ2V0U3RyaW5nKCBwaXBl
bGluZUN1cnNvciwgImVuY29kaW5nIiApOw0KcGlwZWxpbmVDdXJzb3IuZGVzdHJveSgpOw0KDQpp
ZiAoIGVuY29kaW5nID09IG51bGwgfHwgZW5jb2RpbmcuZXF1YWxzKCAiIiApICkgew0KCWVuY29k
aW5nID0gIlVURi04IjsNCn0NCg0KYnl0ZVtdIGlucHV0Qnl0ZXMgPSBudWxsOw0KU3RyaW5nQnVm
ZmVyIHJlc3VsdCA9IG5ldyBTdHJpbmdCdWZmZXIoKTsNCg0KdHJ5IHsNCglpbnB1dEJ5dGVzID0g
aW5wdXRTdHJpbmcuZ2V0Qnl0ZXMoIGVuY29kaW5nICk7DQoJDQoJZm9yICggaW50IGkgPSAwOyBp
IDwgaW5wdXRCeXRlcy5sZW5ndGg7IGkrKyApIHsNCgkJcmVzdWx0LmFwcGVuZCggSW50ZWdlci50
b0hleFN0cmluZyggMHgwMTAwICsgKCBpbnB1dEJ5dGVzWyBpIF0gJiAweDAwRkYgKSApLnN1YnN0
cmluZyggMSApICk7DQoJfQ0KfSBjYXRjaCAoIEV4Y2VwdGlvbiBlICkgew0KCQ0KfQ0KDQppbnB1
dEJ5dGVzID0gbnVsbDsNCg0KSURhdGFDdXJzb3IgcGlwZWxpbmVDdXJzb3JfMSA9IHBpcGVsaW5l
LmdldEN1cnNvcigpOw0KSURhdGFVdGlsLnB1dCggcGlwZWxpbmVDdXJzb3JfMSwgImhleFN0cmlu
ZyIsIHJlc3VsdC50b1N0cmluZygpICk7DQpwaXBlbGluZUN1cnNvcl8xLmRlc3Ryb3koKTs=</value>
</Values>
