<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">isFile</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgcGlwZWxpbmVDdXJzb3IgPSBwaXBlbGluZS5nZXRDdXJzb3IoKTsNClN0cmlu
ZyBmaWxlTmFtZSA9IElEYXRhVXRpbC5nZXRTdHJpbmcoIHBpcGVsaW5lQ3Vyc29yLCAiZmlsZU5h
bWUiICk7DQpwaXBlbGluZUN1cnNvci5kZXN0cm95KCk7DQoNClN0cmluZyBpc0ZpbGUgPSAiIjsN
CkZpbGUgZmlsZSA9IG51bGw7DQoNCnRyeSB7DQoJZmlsZSA9IG5ldyBGaWxlKCBmaWxlTmFtZSAp
Ow0KCQ0KCWlmICggZmlsZS5pc0ZpbGUoKSApIHsNCgkJaXNGaWxlID0gInRydWUiOw0KCX0gZWxz
ZSB7DQoJCWlzRmlsZSA9ICJmYWxzZSI7DQoJfQ0KfSBjYXRjaCAoIEV4Y2VwdGlvbiBlICkgew0K
CQ0KfQ0KDQpJRGF0YUN1cnNvciBwaXBlbGluZUN1cnNvcl8xID0gcGlwZWxpbmUuZ2V0Q3Vyc29y
KCk7DQpJRGF0YVV0aWwucHV0KCBwaXBlbGluZUN1cnNvcl8xLCAiaXNGaWxlIiwgaXNGaWxlICk7
DQpwaXBlbGluZUN1cnNvcl8xLmRlc3Ryb3koKTs=</value>
</Values>
