<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">getBusinessDocSchemaDef</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgcGlwZWxpbmVDdXJzb3IgPSBwaXBlbGluZS5nZXRDdXJzb3IoKTsNClN0cmlu
ZwluYW1lID0gSURhdGFVdGlsLmdldFN0cmluZyggcGlwZWxpbmVDdXJzb3IsICJuYW1lIiApOw0K
cGlwZWxpbmVDdXJzb3IuZGVzdHJveSgpOw0KDQpTdHJpbmcgZXJyb3JNc2cgPSAiIjsNCklEYXRh
IHNjaGVtYURlZiA9IG51bGw7DQoNCnRyeSB7DQoJc2NoZW1hRGVmID0gc01hbmFnZXIuZ2V0QnVz
aW5lc3NEb2NTY2hlbWFEZWYoIG5hbWUgKTsNCgkNCglpZiAoIHNjaGVtYURlZiA9PSBudWxsICkg
ew0KCQllcnJvck1zZyA9IG5hbWUgKyAiIFx1Qzc1OCBTY2hlbWEgXHVDODE1XHVDNzU4XHVBQzAw
IFx1Qzg3NFx1QzdBQ1x1RDU1OFx1QzlDMCBcdUM1NEFcdUMyQjVcdUIyQzhcdUIyRTQuIjsNCgl9
DQp9IGNhdGNoICggRXhjZXB0aW9uIGUgKSB7DQoJZXJyb3JNc2cgPSBlLnRvU3RyaW5nKCk7DQp9
DQoNCklEYXRhQ3Vyc29yIHBpcGVsaW5lQ3Vyc29yXzEgPSBwaXBlbGluZS5nZXRDdXJzb3IoKTsN
CklEYXRhVXRpbC5wdXQoIHBpcGVsaW5lQ3Vyc29yXzEsICJlcnJvck1zZyIsIGVycm9yTXNnICk7
DQpJRGF0YVV0aWwucHV0KCBwaXBlbGluZUN1cnNvcl8xLCAic2NoZW1hRGVmIiwgc2NoZW1hRGVm
ICk7DQpwaXBlbGluZUN1cnNvcl8xLmRlc3Ryb3koKTs=</value>
</Values>
