<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">getSendRecordCount</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgcGlwZWxpbmVDdXJzb3IgPSBwaXBlbGluZS5nZXRDdXJzb3IoKTsNCmludCBt
YXhMZW5ndGggPSBJbnRlZ2VyLnBhcnNlSW50KCBJRGF0YVV0aWwuZ2V0U3RyaW5nKCBwaXBlbGlu
ZUN1cnNvciwgIm1heExlbmd0aCIgKSApOw0KaW50IGhlYWRlckxlbmd0aCA9IEludGVnZXIucGFy
c2VJbnQoIElEYXRhVXRpbC5nZXRTdHJpbmcoIHBpcGVsaW5lQ3Vyc29yLCAiaGVhZGVyTGVuZ3Ro
IiApICk7DQppbnQgcmVjTGVuZ3RoID0gSW50ZWdlci5wYXJzZUludCggSURhdGFVdGlsLmdldFN0
cmluZyggcGlwZWxpbmVDdXJzb3IsICJyZWNMZW5ndGgiICkgKTsNCnBpcGVsaW5lQ3Vyc29yLmRl
c3Ryb3koKTsNCg0KaW50IHNlbmRSZWNDb3VudCA9ICggbWF4TGVuZ3RoIC0gaGVhZGVyTGVuZ3Ro
ICkgLyByZWNMZW5ndGg7DQoNCi8vIHNlbmRSZWNDb3VudFx1QzVEMFx1QzExQyAxXHVDNzQ0IFx1
QkU3Q1x1QzkwMFx1QjJFNC4NCnNlbmRSZWNDb3VudC0tOw0KDQpJRGF0YUN1cnNvciBwaXBlbGlu
ZUN1cnNvcl8xID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQpJRGF0YVV0aWwucHV0KCBwaXBlbGlu
ZUN1cnNvcl8xLCAic2VuZFJlY0NvdW50Iiwgc2VuZFJlY0NvdW50ICsgIiIgKTsNCnBpcGVsaW5l
Q3Vyc29yXzEuZGVzdHJveSgpOw==</value>
</Values>
