<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">putCustomVariable</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgcGlwZWxpbmVDdXJzb3IgPSBwaXBlbGluZS5nZXRDdXJzb3IoKTsNClN0cmlu
Zwl2YXJpYWJsZU5hbWUgPSBJRGF0YVV0aWwuZ2V0U3RyaW5nKCBwaXBlbGluZUN1cnNvciwgInZh
cmlhYmxlTmFtZSIgKTsNCklEYXRhIEN1c3RvbVZhcmlhYmxlSW5mbwk9IElEYXRhVXRpbC5nZXRJ
RGF0YSggcGlwZWxpbmVDdXJzb3IsICJDdXN0b21WYXJpYWJsZUluZm8iICk7DQpwaXBlbGluZUN1
cnNvci5kZXN0cm95KCk7DQoNClN0cmluZyBlcnJvck1zZyA9ICIiOw0KDQp0cnkgew0KCXNNYW5h
Z2VyLnB1dEN1c3RvbVZhcmlhYmxlKCB2YXJpYWJsZU5hbWUsIEN1c3RvbVZhcmlhYmxlSW5mbyAp
Ow0KfSBjYXRjaCAoIEV4Y2VwdGlvbiBlICkgew0KCWVycm9yTXNnID0gZS50b1N0cmluZygpOw0K
fQ0KDQpJRGF0YUN1cnNvciBwaXBlbGluZUN1cnNvcl8xID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7
DQpJRGF0YVV0aWwucHV0KCBwaXBlbGluZUN1cnNvcl8xLCAiZXJyb3JNc2ciLCBlcnJvck1zZyAp
Ow0KcGlwZWxpbmVDdXJzb3JfMS5kZXN0cm95KCk7</value>
</Values>
