<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">stringListToString</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IJcGlwZWxpbmVDdXJzb3IJPSBwaXBlbGluZS5nZXRDdXJzb3IoKTsNClN0cmlu
Z1tdIGluU3RyaW5nTGlzdCA9IElEYXRhVXRpbC5nZXRTdHJpbmdBcnJheSggcGlwZWxpbmVDdXJz
b3IsICJpblN0cmluZ0xpc3QiICk7DQpTdHJpbmcgc2VwYXJhdG9yRW50ZXIgPSBJRGF0YVV0aWwu
Z2V0U3RyaW5nKCBwaXBlbGluZUN1cnNvciwgInNlcGFyYXRvckVudGVyIiApOw0KU3RyaW5nIHNl
cGFyYXRvciA9IElEYXRhVXRpbC5nZXRTdHJpbmcoIHBpcGVsaW5lQ3Vyc29yLCAic2VwYXJhdG9y
IiApOwkJDQpwaXBlbGluZUN1cnNvci5kZXN0cm95KCk7DQoNClN0cmluZ0J1ZmZlciBzdHJCdWZm
ZXIgPSBuZXcgU3RyaW5nQnVmZmVyKCk7DQpTdHJpbmcgb3V0U3RyaW5nID0gIiI7DQoNCmlmICgg
c2VwYXJhdG9yRW50ZXIuZXF1YWxzKCAidHJ1ZSIgKSApIHsNCglzZXBhcmF0b3IgPSAiXG4iOw0K
fQ0KDQpmb3IgKCBpbnQgaSA9IDA7IGkgPCBpblN0cmluZ0xpc3QubGVuZ3RoOyBpKysgKSB7DQoJ
aWYgKCBpID09IDAgKSB7DQoJCXN0ckJ1ZmZlci5hcHBlbmQoIGluU3RyaW5nTGlzdFsgaSBdICk7
DQoJfSBlbHNlIHsNCgkJc3RyQnVmZmVyLmFwcGVuZCggc2VwYXJhdG9yICk7DQoJCXN0ckJ1ZmZl
ci5hcHBlbmQoIGluU3RyaW5nTGlzdFsgaSBdICk7DQoJfQ0KfQ0KDQpvdXRTdHJpbmcgPSBzdHJC
dWZmZXIudG9TdHJpbmcoKTsNCg0Kc3RyQnVmZmVyID0gbnVsbDsNCg0KSURhdGFDdXJzb3IgcGlw
ZWxpbmVDdXJzb3JfMSA9IHBpcGVsaW5lLmdldEN1cnNvcigpOw0KSURhdGFVdGlsLnB1dCggcGlw
ZWxpbmVDdXJzb3JfMSwgIm91dFN0cmluZyIsIG91dFN0cmluZyApOw0KcGlwZWxpbmVDdXJzb3Jf
MS5kZXN0cm95KCk7</value>
</Values>
