<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">putBusinessName</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgcGlwZWxpbmVDdXJzb3IgPSBwaXBlbGluZS5nZXRDdXJzb3IoKTsNClN0cmlu
ZwluYW1lID0gSURhdGFVdGlsLmdldFN0cmluZyggcGlwZWxpbmVDdXJzb3IsICJuYW1lIiApOw0K
SURhdGEgQnVzaW5lc3NOYW1lSW5mbwk9IElEYXRhVXRpbC5nZXRJRGF0YSggcGlwZWxpbmVDdXJz
b3IsICJCdXNpbmVzc05hbWVJbmZvIiApOw0KcGlwZWxpbmVDdXJzb3IuZGVzdHJveSgpOw0KDQpT
dHJpbmcgZXJyb3JNc2cgPSAiIjsNCg0KLy8gQnVzaW5lc3NOYW1lTGlzdCBIYXNodGFibGUgQ3Jl
YXRpb24uDQovL2NyZWF0ZUJ1c2luZXNzTmFtZUxpc3QoKTsNCg0KdHJ5IHsNCgkvL0J1c2luZXNz
TmFtZUxpc3QucHV0KCBuYW1lLCBCdXNpbmVzc05hbWVJbmZvICk7DQoJc01hbmFnZXIucHV0QnVz
aW5lc3NOYW1lKCBuYW1lLCBCdXNpbmVzc05hbWVJbmZvICk7DQp9IGNhdGNoICggRXhjZXB0aW9u
IGUgKSB7DQoJZXJyb3JNc2cgPSBlLnRvU3RyaW5nKCk7DQp9DQoNCklEYXRhQ3Vyc29yIHBpcGVs
aW5lQ3Vyc29yXzEgPSBwaXBlbGluZS5nZXRDdXJzb3IoKTsNCklEYXRhVXRpbC5wdXQoIHBpcGVs
aW5lQ3Vyc29yXzEsICJlcnJvck1zZyIsIGVycm9yTXNnICk7DQpwaXBlbGluZUN1cnNvcl8xLmRl
c3Ryb3koKTs=</value>
</Values>
