<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">getByteLength</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IJcGlwZWxpbmVDdXJzb3IJPSBwaXBlbGluZS5nZXRDdXJzb3IoKTsNClN0cmlu
ZyBjb250ZW50ID0gSURhdGFVdGlsLmdldFN0cmluZyggcGlwZWxpbmVDdXJzb3IsICJjb250ZW50
IiApOw0KU3RyaW5nIGNoYXJzZXQgPSBJRGF0YVV0aWwuZ2V0U3RyaW5nKCBwaXBlbGluZUN1cnNv
ciwgImNoYXJzZXQiICk7DQpwaXBlbGluZUN1cnNvci5kZXN0cm95KCk7DQoNCmlmICggY2hhcnNl
dCA9PSBudWxsICkgew0KCWNoYXJzZXQgPSAiIjsNCn0NCg0KU3RyaW5nIGJ5dGVMZW5ndGggPSAi
MCI7DQoNCnRyeSB7DQoJaWYgKCBjaGFyc2V0LmVxdWFscyggIiIgKSApIHsNCgkJYnl0ZUxlbmd0
aCA9ICggY29udGVudC5nZXRCeXRlcygpICkubGVuZ3RoICsgIiI7DQoJfSBlbHNlIHsNCgkJYnl0
ZUxlbmd0aCA9ICggY29udGVudC5nZXRCeXRlcyggY2hhcnNldCApICkubGVuZ3RoICsgIiI7DQoJ
fQ0KfSBjYXRjaCAoIEV4Y2VwdGlvbiBlICkgew0KCQ0KfQ0KDQpJRGF0YUN1cnNvciBwaXBlbGlu
ZUN1cnNvcl8xID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQpJRGF0YVV0aWwucHV0KCBwaXBlbGlu
ZUN1cnNvcl8xLCAiYnl0ZUxlbmd0aCIsIGJ5dGVMZW5ndGggKTsNCnBpcGVsaW5lQ3Vyc29yXzEu
ZGVzdHJveSgpOw==</value>
</Values>
