<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">getPropertyValue</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgcGlwZWxpbmVDdXJzb3IgPSBwaXBlbGluZS5nZXRDdXJzb3IoKTsJCQ0KU3Ry
aW5nIHByb3BOYW1lID0gSURhdGFVdGlsLmdldFN0cmluZyggcGlwZWxpbmVDdXJzb3IsICJwcm9w
TmFtZSIgKTsNClN0cmluZyBwcm9wRnVsbEZpbGVOYW1lID0gSURhdGFVdGlsLmdldFN0cmluZygg
cGlwZWxpbmVDdXJzb3IsICJwcm9wRnVsbEZpbGVOYW1lIiApOw0KcGlwZWxpbmVDdXJzb3IuZGVz
dHJveSgpOw0KDQpQcm9wZXJ0aWVzIHByb3AgPSBuZXcgUHJvcGVydGllcygpOw0KRmlsZUlucHV0
U3RyZWFtIGZpcyA9IG51bGw7DQpTdHJpbmcgcHJvcFZhbHVlID0gIiI7DQoNCnRyeSB7DQoJZmlz
ID0gbmV3IEZpbGVJbnB1dFN0cmVhbSggcHJvcEZ1bGxGaWxlTmFtZSApOw0KCXByb3AubG9hZCgg
ZmlzICk7DQoJcHJvcFZhbHVlID0gcHJvcC5nZXRQcm9wZXJ0eSggcHJvcE5hbWUgKTsNCn0gY2F0
Y2ggKCBFeGNlcHRpb24gZSApIHsNCgl0aHJvdyBuZXcgU2VydmljZUV4Y2VwdGlvbiggcHJvcE5h
bWUgKyAiIFByb3BlcnR5IEdldCBFcnJvciA9PT4gIiArIGUgKTsNCn0gZmluYWxseSB7DQoJaWYg
KCBmaXMgIT0gbnVsbCApIHsNCgkJdHJ5IHsNCgkJCWZpcy5jbG9zZSgpOw0KCQl9IGNhdGNoICgg
RXhjZXB0aW9uIGZlICkgew0KCQkJDQoJCX0NCgl9DQp9DQoNCnByb3AgPSBudWxsOw0KZmlzID0g
bnVsbDsNCg0KSURhdGFDdXJzb3IgcGlwZWxpbmVDdXJzb3JfMSA9IHBpcGVsaW5lLmdldEN1cnNv
cigpOw0KSURhdGFVdGlsLnB1dCggcGlwZWxpbmVDdXJzb3JfMSwgInByb3BWYWx1ZSIsIHByb3BW
YWx1ZSApOw0KcGlwZWxpbmVDdXJzb3JfMS5kZXN0cm95KCk7</value>
</Values>
