<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">putBusinessInterface</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgcGlwZWxpbmVDdXJzb3IgPSBwaXBlbGluZS5nZXRDdXJzb3IoKTsNClN0cmlu
ZwluYW1lID0gSURhdGFVdGlsLmdldFN0cmluZyggcGlwZWxpbmVDdXJzb3IsICJuYW1lIiApOw0K
SURhdGEgQnVzaW5lc3NJbnRlcmZhY2VJbmZvCT0gSURhdGFVdGlsLmdldElEYXRhKCBwaXBlbGlu
ZUN1cnNvciwgIkJ1c2luZXNzSW50ZXJmYWNlSW5mbyIgKTsNCnBpcGVsaW5lQ3Vyc29yLmRlc3Ry
b3koKTsNCg0KU3RyaW5nIGVycm9yTXNnID0gIiI7DQoNCnRyeSB7DQoJc01hbmFnZXIucHV0QnVz
aW5lc3NJbnRlcmZhY2UoIG5hbWUsIEJ1c2luZXNzSW50ZXJmYWNlSW5mbyApOw0KfSBjYXRjaCAo
IEV4Y2VwdGlvbiBlICkgew0KCWVycm9yTXNnID0gZS50b1N0cmluZygpOw0KfQ0KDQpJRGF0YUN1
cnNvciBwaXBlbGluZUN1cnNvcl8xID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQpJRGF0YVV0aWwu
cHV0KCBwaXBlbGluZUN1cnNvcl8xLCAiZXJyb3JNc2ciLCBlcnJvck1zZyApOw0KcGlwZWxpbmVD
dXJzb3JfMS5kZXN0cm95KCk7</value>
</Values>
